title: Meadow's Musings
description: The life and times of a distinguished Miniature Schnauzer running things at Clayton & Fell
baseurl: "/meadow-blog"
url: "https://jestrada.github.io"

theme: minima

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
